use ret_core::r_installation::RInstallation;
use std::{env, fs, path::PathBuf};
use ts_rs::TS;

fn main() {
    let output_dir = env::args_os()
        .nth(1)
        .map(PathBuf::from)
        .expect("usage: cargo run -p ret-core --example export-protocol-ts -- <output-dir>");

    RInstallation::export_all_to(&output_dir).expect("failed to export RET protocol types");

    let index = [
        "// This file was generated by ts-rs. Do not edit this file manually.",
        "export type { Architecture } from './Architecture';",
        "export type { DiscoverySource } from './DiscoverySource';",
        "export type { EnvManager } from './EnvManager';",
        "export type { EnvManagerType } from './EnvManagerType';",
        "export type { LocatorMetadata } from './LocatorMetadata';",
        "export type { RInstallation } from './RInstallation';",
        "export type { RInstallationKind } from './RInstallationKind';",
        "export type { RVersionsOverlay } from './RVersionsOverlay';",
        "",
    ]
    .join("\n");

    fs::write(output_dir.join("index.ts"), index).expect("failed to write RET protocol index");
}
